name: Ultralytics application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: checkout out repository
    - uses: actions/setup-python@v3
      name: Set up Python 3.10
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Test with pytest
      run: pytest
        
